os:
  - linux
  - osx
language: node_js
node_js: stable
install:
  - rvm install 2.3.3
  - gem install bundler
  - npm install
  - bundle install
script:
  - npm run lint
  - bundle exec jekyll build
notifications:
  email: false
