os:
  - linux
  - osx
language: node_js
node_js:
  - "7"
rvm:
  - "2.3"
install:
  - gem install jekyll
  - gem install bundler
  - npm install
  - bundle install
script:
  - npm run lint
  - bundle exec jekyll build
notifications:
  email: false
