language: node_js
node_js: stable
install:
  - rvm install 2.3.3
  - gem install bundler
  - npm install
  - bundle install
script:
  - npm run lint
  - bundle exec jekyll build
cache:
  bundler: true
  directories:
    - node_modules
    - _site
notifications:
  email: false
