host: 0.0.0.0
author: Avery Magnotti
alias: citrusui
email: averymagnotti@outlook.com
url: https://dev.citrusui.me
twitter: citrusui
github: https://github.com/citrusui/me
paypal: AveryMagnotti
brand_color: "#1e1e1e"
cdnjs:
  url: https://cdnjs.cloudflare.com/ajax/libs
  simple-jekyll-search:
    name: simple-jekyll-search
    version: 1.1.8
    file: jekyll-search
    hash: sha256-YHAdSiDznyIEAhUYsPerIh6qoIktpxz9zJ47AtrFFGs=
  lazysizes:
    name: lazysizes
    version: 3.0.0
    hash: sha256-3aNzF0qAl+dcYi1jq/8xNvw6wR5tzgo4AOAacEleQVk=
sass:
  sass_dir: _includes/poole/scss
  style: :compressed
exclude:
  - node_modules
  - .hound.yml
  - .sass-lint.yml
  - .travis.yml
  - CNAME
  - firebase.json
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - package.json
  - README.md
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
paginate: 4
paginate_path: "/blog/page/:num"
