incremental: true
highlighter: none
author: Avery Magnotti
email: averymagnotti@outlook.com
url: https://citrusui.me
twitter: citrusui
github: https://github.com/citrusui/me
paypal: citrusui
brand_color: "#1e1e1e"
cdnjs:
  url: https://cdnjs.cloudflare.com/ajax/libs
  prism:
    name: prism
    version: 1.15.0
    hash: sha256-jc6y1s/Y+F+78EgCT/lI2lyU7ys+PFYrRSJ6q8/R8+o=
  prism-bash:
    file: prism-bash
    hash: sha256-X3YM6tquRzazP7osGUAP+f89IAGl/NPYzIyEkJn5qDU=
  prism-markup:
    file: prism-markup
    hash: sha256-QciVGr0G0qBC7iVqTH0zo6B2h4sFTL5iyxA3vO0Mu2M=
  simple-jekyll-search:
    name: simple-jekyll-search
    version: 1.7.0
    hash: sha256-U31KL506Dkhr1NBRpFgPKiVvLXnlZhmFDPbNTbw732c=
  lazysizes:
    name: lazysizes
    version: 4.1.4
    hash: sha256-TAKkT1A7MjH+laNK0pwZ92ns2lMF7VlqJt/E5rIJ/rI=
sass:
  sass_dir: _includes/scss
  style: :compressed
include: ['_pages']
exclude:
  - node_modules
  - .hound.yml
  - .sass-lint.yml
  - .travis.yml
  - CNAME
  - firebase.json
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - package.json
  - README.md
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
paginate: 4
paginate_path: "/blog/page/:num/"
