permalink: pretty
author: Avery Magnotti
email: averymagnotti@outlook.com
url: https://citrusui.me
description:
  - The clean and simple portfolio of Avery Magnotti (citrusui). I make websites with modern technologies.
twitter: citrusui
github: https://github.com/citrusui/me
paypal: AveryMagnotti
brand_color: "#4ea5d9"
sass:
  sass_dir: _sass
  style: :compressed
cdn:
  ga-lite: https://cdnjs.cloudflare.com/ajax/libs/ga-lite/1.1.0/ga-lite.min.js
  turbolinks: https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.0.0/turbolinks.min.js
sri:
  ga-lite: sha256-ajtrRiwBtHYY00ij7nHaPHhPxPSyegvxH7B/bPk7meI=
  turbolinks: sha256-HUtkNsGc3BlCNQTNPUr5JsjW0wQFeU4nfYOEuUcxptU=
exclude:
  - node_modules
  - .hound.yml
  - .sass-lint.yml
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - package.json
  - README.md
gems:
  - jekyll-redirect-from
